#ifndef IMG_H
#define IMG_H


static const char* const image0_data[] = { 
"75 66 256 2",
"#D c #747474",
"#t c #898989",
"#u c #949494",
"aB c #9aaeb5",
"#l c #9f9f9f",
"aC c #a1b9c3",
".H c #a27d22",
"#m c #a2a2a2",
"bR c #a3a39e",
".E c #a5832a",
"bY c #a7a7a3",
".2 c #a7a7a7",
"b2 c #a8a4aa",
"bS c #a8a8a4",
"ak c #a8b7b9",
".x c #aa8a35",
"al c #abc1c8",
"#n c #acacac",
"aD c #acc8d4",
"bZ c #adaab0",
".3 c #afaeaa",
"#v c #b0b0b0",
".w c #b3964b",
"b3 c #b3afb5",
"bQ c #b3b0b6",
".P c #b5b5b5",
"an c #b5cdd5",
"bX c #b6b5b1",
"am c #b6c6ca",
".0 c #ba9e52",
"b4 c #bab6bc",
"#e c #bab9b7",
"ao c #bad2da",
"aE c #bad9e7",
".Q c #bbbbbb",
".B c #bfa14f",
".N c #bfa86b",
".7 c #c0ad7d",
".4 c #c0bfc0",
"#q c #c19e4f",
"aF c #c1e1f0",
"#y c #c2b07f",
".R c #c2c2c2",
"ap c #c3d5db",
"bI c #c5c5bf",
"#w c #c6c4c6",
"aG c #c6e8f6",
"aq c #c7dce2",
".C c #c9ac65",
".O c #c9c8c8",
".S c #c9cbcb",
"aH c #caecfa",
"bK c #cbc7d1",
"bW c #cbcbc4",
".D c #ccba88",
"ar c #cde3e9",
"aI c #cdeffe",
"bP c #d0cbd7",
"bB c #d0cfcc",
".T c #d2d3d1",
"as c #d2ecf3",
"aJ c #d2f2ff",
"bT c #d3d3c8",
"bz c #d4d2dc",
"bd c #d5dbdb",
"#p c #d6c79a",
".J c #d6c8a4",
"bO c #d6d5e0",
"aU c #d6f3ff",
".M c #d7be7a",
".8 c #d8c07e",
"bM c #d8d7e2",
".U c #d8d8d8",
"bL c #d9d8e2",
"aZ c #d9f4ff",
"bN c #dadae4",
"bJ c #dbdde7",
"bU c #dcdbd2",
"b6 c #dcdbe5",
".5 c #dcdcdc",
"bc c #dcdfe9",
"a4 c #dcf5ff",
"b8 c #dddce5",
"at c #ddf2f6",
"aK c #ddf5fd",
"be c #dee2ec",
"#U c #dee6f8",
".v c #dfd4b5",
".V c #dfe0df",
"bA c #dfe4f0",
"#T c #dfe7f8",
"aV c #dff5ff",
"bt c #e0e7f5",
"#9 c #e0e7f8",
"#8 c #e0e8f8",
"b7 c #e1dfe6",
"bf c #e1e6f1",
"#S c #e1e8f8",
"#7 c #e1e9f8",
"a6 c #e1f6ff",
"bv c #e2e7f3",
"#3 c #e2e9f8",
".A c #e3dec9",
"#x c #e3e1d9",
"#K c #e3eaf9",
"aL c #e3f6fa",
"#f c #e4e2d2",
".6 c #e4e5e4",
"bs c #e4e9f6",
"#J c #e4eaf9",
"bh c #e4ecf0",
"b. c #e4f7ff",
"b1 c #e5e3e9",
"bu c #e5e9f4",
"br c #e5ebf7",
"#I c #e5ecf9",
"au c #e5f5f5",
"aM c #e5f7fa",
"ab c #e7edf9",
"#2 c #e7edfa",
"a5 c #e7f8ff",
"#E c #e8e2cd",
"b5 c #e8e7db",
".W c #e8e8e5",
"af c #e8eef9",
".d c #e8eefa",
"bw c #e9e7d6",
"bj c #e9eef3",
".n c #e9eefa",
".p c #e9effa",
"av c #e9f7f4",
"aN c #e9f9f8",
"#o c #eaeaea",
".o c #eaeffa",
"a7 c #eaf9ff",
"#b c #ebd59a",
"bE c #ebeadd",
"aY c #ebeff8",
".j c #ebf0fa",
".u c #ece5d3",
"bx c #ece9d8",
".c c #ecf1fb",
"#N c #edeada",
"ae c #edf1f8",
".t c #edf2fa",
"aw c #edf9f6",
"b# c #edfaff",
"bV c #eeeed9",
"a3 c #eef2f8",
".r c #eef2fb",
"aO c #eefaf8",
"#z c #efeddd",
".I c #efeee0",
"#L c #eff0f1",
".q c #eff3fc",
".G c #f0daa5",
"ag c #f0f1ea",
".1 c #f0f3fb",
"#k c #f0f3fc",
"aQ c #f0f4f7",
".i c #f0f4fc",
"aW c #f1f2df",
"ad c #f1f5f6",
"ax c #f1fbf6",
"bC c #f2f0e1",
"#H c #f2f5fa",
".g c #f2f5fc",
"ba c #f2fbf9",
"bg c #f2fbff",
"bF c #f3f1e5",
".b c #f3f6fc",
"aR c #f3fbf4",
".F c #f4e2b2",
".L c #f4e5bd",
"by c #f4f2e2",
"bD c #f4f3e4",
"#M c #f4f6f5",
"aP c #f5f4e4",
"a# c #f5f4e9",
"a1 c #f5f6e2",
"a. c #f5f6f2",
"#C c #f5f7f8",
".m c #f5f7fd",
"ay c #f5fcf9",
".Z c #f6eaca",
"aj c #f6f8f2",
".h c #f6f8fd",
"aS c #f6fcf1",
"az c #f6fcf5",
"bi c #f6fcff",
".X c #f7ecd1",
".y c #f7f6ef",
"bp c #f7f7e6",
"#G c #f7f8f5",
".l c #f7f9fd",
"a0 c #f7fcee",
"#r c #f8f6ea",
"bb c #f8f8e0",
"#B c #f8f8f9",
"#X c #f8f9f3",
"#F c #f8faf3",
".s c #f8fafd",
"bk c #f8fdff",
"#h c #f9f3e2",
"## c #f9f8e5",
"bG c #f9f8e9",
"aA c #f9faee",
".f c #f9fafe",
"#1 c #f9fdf1",
"#d c #fafbfc",
".a c #fafbfe",
"#R c #fafced",
"b9 c #fafcfe",
"a2 c #fafdeb",
"#O c #fafdf4",
"#s c #fafdf8",
"bl c #fafefc",
"a8 c #fbfae5",
"bH c #fbfbe8",
"#c c #fbfcfb",
".k c #fbfcfe",
"bm c #fbfeff",
"bo c #fcfce2",
"bn c #fcfefe",
".K c #fdf5da",
"#g c #fdf9ed",
"#a c #fdfce4",
"ac c #fdfce7",
".e c #fdfdfe",
"a9 c #fdfee7",
"#Q c #fdfee9",
"#j c #fdfefc",
"aa c #fee9ae",
"aX c #feefba",
"#i c #fef4cc",
".9 c #fef6d3",
"#Z c #fefbdc",
"#Y c #fefde4",
"aT c #fefee4",
".Y c #fefef1",
"b0 c #fefefe",
".# c #fefeff",
"#A c #fefff6",
"bq c #fefffe",
".z c #feffff",
"#5 c #ffefb4",
"ai c #fff2bd",
"ah c #fff3c4",
"#6 c #fff9d4",
"#0 c #ffffe3",
"#4 c #ffffe7",
"#P c #ffffed",
"#. c #fffff9",
"#W c #fffffc",
"#V c #fffffe",
"Qt c #ffffff",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.a.b.c.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.e.f.g.c.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.f.h.i.j.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.k.l.m.b.c.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.k.h.m.m.i.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.a.h.m.m.b.c.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.k.l.h.h.m.i.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.e.l.h.h.h.h.i.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.f.h.h.h.h.m.q.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.k.l.h.h.h.h.m.r.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.#.s.l.h.h.h.h.m.t.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.u.vQtQtQtQt.k.l.l.l.h.h.h.m.t.c.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.w.x.yQt.z.a.l.l.l.l.h.h.m.r.t.c.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.A.B.C.D.#.e.a.s.l.l.l.h.m.q.r.t.c.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.E.F.G.H.I.e.k.a.f.s.l.m.q.r.r.t.c.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt.J.C.K.L.M.N.e.e.k.a.s.l.i.q.r.r.t.c.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQt.O.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.Q.R.S.T.U.V.W.W.D.E.X.Y.Z.Z.0.w.I.e.e.k.l.h.b.1.r.t.c.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQt.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.2.3.P.4.S.T.5.6.7.E.8.9.Y#..Z###a#b.x.N.y#c#d.s.l.m.i.q.c.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQt.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P.P#e.R.O.T.U.V.W#f.E.C.F.K###g#g.Z#h#h.K#i.8.x.v#j#c#c.s.h.g#k.r.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQt#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#l#m#n.P.4.S.U.V#o#p.H#q#b.L.X#h.Z.X.L.F.M.E.D#r#.#s#c#d.h.b.q.r.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQt#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#t#u#m#v.Q#w.T.V#x#y.x.M.K#..Z.G.M.x.N#z#A#A#A#A#s#B#C.i.r.c.c.c.j.j.j.o.o.p.n.n.d.d.d.d.d.d",
"QtQtQtQtQt#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#D#t#l#n#e#w.T.5#x.w#p#g.X#b.x#E#A#A.Y.Y.Y.Y#F#G#C#H.r.c.c.c.j.j.j.o.o.p.n.n.d.d.d#I#J#K",
"QtQtQtQtQt.P.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.U.5.V.6.W#o#L#L#M#N.E.9.Z.w.J#O.Y.Y#P#P#Q#R#F#G#C#H.q.c.c.c.j.j.j.o.o.n#I#K#S#T#U#U#U#U",
"QtQtQtQtQt.QQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#V#V#W#W#V#V#W#V.D.8#b.x#B#X#P#P#Y#Z#0#Q#1#X#C#H.q.c.c.c.j.j#2#I#3#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.RQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#V#W#W#W#W#W#W.y.x.0.A#G#h#Z#4#5#6#0#Q#R#F#G#H.1.c.j.d#I#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.4QtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#V#W#W#W#W#W#W#W.D.w#Wa.a#aa#i#i#0#0#Q#R#F#G#H.tab#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.QQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#V#W#W#W#.#.#W#W#W#V#Wa..yac.K.K.9#0#Q#R#Xadaeaf#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.PQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#W#W#.#.#.#.#W#W#W#.ag#r#iah#Zai#Z#Q#Rajadaeaf#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.Pakakalalamamananaoaoapapaqaqaqarararararasasasasasasasasasatauauavavawaxay#sazaga#.9#0#0#0#0#QaAajadaeaf#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#vaBaBaCaCaCalaDaDaDanaoaEaEaEaEaFaFaFaGaGaGaHaHaHaIaIaIaIaIaJaKaLaMaNaNaOayayayagaP#Q#0ai#0#0#QaAa.adaeaf#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#naBalaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaKaLaMaNaNaxayayaz.IaP#Q#0aiah#6ahaAa.aQaeab#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.2akaDaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaJaKaMaMawawaxaRazaS.IaP#QaT.9.K#i#aaAa.aQ.jab#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#makanaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaUaVaMaNawawaxaRazaSaWaP#QaXai.9#6#QaA#MaQaY#I#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#lalaoaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaZaVaMaNaOaxaxaSaSa0aWa1#Q#0#0#0#5a2ajada3.n#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#lamaoa4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4a4aVa5aOaOaRaRaSaSa2aWa1#Q#0#Z#0aTa2ajadaeab#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#uamapaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVaVa6a7aOaxaRaSaSa0a2aWa8a9#Z#5#0a9aAa.aQ.j#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#uamaqa6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6a6b.a7aOaxaRaSaSa2a2a1##ahah.9#i#ZaA#Ma3.p#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#u.Saqb.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.b.a5b#baaRaz#1#1a2a2a1###Z.9.K#6a2ajaQ.jab#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#uapara5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a5a7b#baazaS#1#Ra2#Qbba8#0#0aXa9aA#Ma3.p#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#l.Tbca7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7a7b#baayaz#1#1a2a2a9bb#Z#0#0#0#Q#Xad.jab#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#lbdbeb#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#b#ayay#O#1#R#Q#Qa9.K#5#0#0a9aA#Ma3.n#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#lbdbfbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgay#O#O#1a2a2#4aX#i.9#Z#0a2ajaQ.j#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt#m.Vbhbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbgbi#s#O#O.Y#Q#Q#4aT#i#Z#6a9aA#Mae.d#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.2.Vbjbibibibibibibibibibibibibibibibibibibibibibibibibibibibi#s#s.Y.Y#Q#Qa9a9#0#6#0aTaA#Ma3.p#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQt#VQt.2.6#Lbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbkbl#s#A.Y#P#Q#i#6#0#0#0#0#RajaQ.j#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQt#W#WQt#n.Wadbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbmbn#j#A.Y#P#Q#5ah#0#0#0bobpajaQ.jafab#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"Qt#A#P#A#V#n#o#C.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.z.zbq#W#A.Y#P#P#4#6.9ah#0#0aW#oaQaYbrbrbrbrbrbsbsbsbsbs#S#Sbtbtbtbt#9#T#T#U#U#U#U#U#U#U",
"Qt.Y#0#P#W#vag#BQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQtQt#V#W#A.Y#P#Y#4#4#Z#0#0#4#P#x.Vbjbubububvbvbvbvbvbvbvbfbvbtbfbtbtbtbt#T#T#U#U#U#U#U#U#U",
"Qt#.#4#4#A#ebwbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbx#zbyaP##a8aXaXaT#0#0#0#a##aP.TbzbfbfbfbfbfbfbfbAbAbAbAbAbAbAbAbAbfbt#9#T#T#U#U#U#U#U#U#U",
"Qt#W.Y#0#PbB#Nbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbxbx#NbCbDbp##a8a8#i.9#Z#0aTa8bpbDbC.O.SbebebebebebebebebebebebebebAbAbtbt#8#9#T#T#U#U#U#U#U#U#U",
"QtQt#.#P#0bEby#z#Nbxbxbxbxbxbxbxbxbxbxbxbxbxbxbx#NbCbCbCbFa#bGbGbbaX#6aT#Z#0#0a9bHbG#ra##zbI.SbJbJbJbJbJbJbJbJbJbJbcbcbebAbf#S#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQt#V#.#P#Ya8bpby.I#z#N#Nbxbxbxbxbxbx#N#N#N#N#NbF.ya##rbGbHbH#Zaiah#i#0aT#aa8bG#ra#bF#f#NbIbKbLbLbLbLbMbMbMbLbNbJbcbebf#S#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQt#W#..IaT#Ya8##bpaPbDbybybCbCbCbCbCbCbFbyby#rbGbp##a8#aaT#6#6#0#Y#Q##bpaPbF.I#Nbx.Abx.R#wbzbzbzbzbzbzbObMbNbcbAbv#3#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQt#VbB###a#0aT#Y#aa8a8####################bHac#aaT#0#0#0aT#abb##.YaPbFbC#z#Nbxbx.Abx#e.QbPbPbPbPbPbzbObJbebfbs#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.2bCaPbpa8#YaT#0#0aTaT#Y#Y#Y#a#a#Y#YaT#0#0#0aT#Ybo##a1bybybD#Nbw#f.A.A.A.A.A.Abx.3bQbKbKbKbPbzbNbcbAbsbr#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQt.e#B#tbRbS.3#ebIbTbU#fbVaWbbboaT#0#0#0bobba1bVbw#fbUbTbWbI.QbX.3bYbRbRbRbRbRbRbRbRbR#ubZbKbKbPbObcbAbvbr#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"Qtb0#B#Lb1bZb2b2b2b2bZb3b4.4.ObB.TbU#xb5bEb5#x#xbU.TbB.O#w.4b4b3bZb2b2b2b2b2b2b2b2b2b2b2b2b2b4bPbzb6bebvbr#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"Qt.e#B#L#ob1b1b7b7b7b7b7b7b7b7b7b7b1b1b1b1b1b1b1b1b1b7b7b7b8b8b8b8b8b8b8b8b8b6b6b6b6b6bNbNbNb8bcbfbubr#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQtQt.#.#.e.e.k.k.kb9.a.a.a.a.f.s.s.s.l.l.l.h.h.m.m.b.b.g.g.g.i.i.i.q.q.r.t.c.c.c.j.j.j.o.p.n.d.d#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQtQt.#.#.e.e.e.k.k.kb9.a.a.a.a.f.s.s.s.l.l.h.h.h.m.m.b.b.g.g.g.i.i.i.q.q.r.t.c.c.c.j.j.j.o.p.n.d.d#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQt.z.#.e.e.e.e.k.k.kb9.a.a.a.a.f.s.s.s.l.l.h.h.h.m.m.b.b.g.g.g.i.i.i.q.q.r.t.c.c.c.j.j.j.o.p.n.d.d#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQtQt.#.#.e.e.e.e.k.k.kb9.a.a.a.a.f.s.s.s.l.l.h.h.h.m.m.b.b.g.g.g.i.i.i.q.q.r.t.c.c.c.j.j.j.o.p.n.d.d#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQt.z.#.e.e.e.e.e.k.k.kb9.a.a.a.a.f.s.s.s.l.l.h.h.h.m.m.b.b.g.g.g.i.i.i.q.q.r.t.c.c.c.j.j.j.o.p.n.d.d#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"QtQt.#.#.e.e.e.e.e.k.k.kb9.a.a.a.a.f.s.s.s.l.l.h.h.h.m.m.b.b.g.g.g.i.i.i.q.q.r.t.c.c.c.j.j.j.o.p.n.d.d#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"Qt.#.#.#.e.e.e.e.e.k.k.kb9.a.a.a.a.f.s.s.s.l.l.h.h.h.m.m.b.b.g.g.g.i.i.i.q.q.r.t.c.c.c.j.j.j.o.p.n.d.d#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U",
"Qt.#.#.#.e.e.e.e.e.k.k.kb9.a.a.a.a.f.s.s.l.l.l.h.h.h.m.m.b.b.g.g.g.i.i.i.q.q.r.t.c.c.c.j.j.j.o.p.n.d.d#2#2#I#I#I#I#J#J#K#K#3#7#S#8#9#T#T#U#U#U#U#U#U#U"};

#endif // IMG_H