#ifndef SOQTLIB
#define SOQTLIB

#include <Inventor/Qt/SoQt.h>
#include <Inventor/nodes/SoCube.h>
#include <Inventor/nodes/SoCone.h>
#include <Inventor/nodes/SoSphere.h>
#include <Inventor/nodes/SoCylinder.h>
#include <Inventor/nodes/SoNode.h>
#include <Inventor/nodes/SoTransform.h>
#include <Inventor/actions/SoLineHighlightRenderAction.h>
#include <Inventor/nodes/SoEventCallback.h> 
#include <Inventor/events/SoMouseButtonEvent.h> 
#include <Inventor/Qt/viewers/SoQtFullViewer.h>
#include <Inventor/Qt/viewers/SoQtConstrainedViewer.h>
#include <Inventor/nodes/SoPerspectiveCamera.h>
#include <Inventor/nodes/SoSelection.h>
#include <Inventor/nodes/SoDirectionalLight.h>
#include <Inventor/nodes/SoMaterial.h>
#include <Inventor/nodes/SoSeparator.h>
#include <Inventor/SbLinear.h>
#include <Inventor/nodes/SoEventCallback.h>
#include <Inventor/events/SoKeyboardEvent.h>
#include <Inventor/sensors/SoTimerSensor.h>
#include <Inventor/actions/SoWriteAction.h>
#include <Inventor/actions/SoBoxHighlightRenderAction.h>
#include <Inventor/SoPickedPoint.h>
#include <Inventor/lists/SbPList.h>
#include <Inventor/actions/SoSearchAction.h>
#include <Inventor/nodekits/SoBaseKit.h>
#include <Inventor/nodekits/SoShapeKit.h>
#include <Inventor/nodes/SoInfo.h>
#include <Inventor/nodes/SoCallback.h>
#include <Inventor/VRMLnodes/SoVRMLGroup.h>
#include <Inventor/nodes/SoLabel.h> 
#include <Inventor/nodes/SoTexture2.h> 
#include <Inventor/nodes/SoFaceSet.h> 
#include <Inventor/nodes/SoCoordinate3.h> 
#include <Inventor/nodes/SoTexture2Transform.h>
#include <Inventor/VRMLnodes/SoVRMLBackground.h> 
#include <Inventor/VRMLnodes/SoVRMLOrientationInterpolator.h> 
#include <Inventor/VRMLnodes/SoVRMLTimeSensor.h> 
#include <Inventor/VRMLnodes/SoVRMLElevationGrid.h>
#include <Inventor/nodes/SoRotation.h> 
#include <Inventor/engines/SoInterpolateRotation.h> 
#include <Inventor/engines/SoOneShot.h> 
#include <Inventor/engines/SoCompose.h> 
#include <Inventor/nodekits/SoSceneKit.h> 
#include <Inventor/actions/SoToVRML2Action.h> 
#include <Inventor/nodes/SoTranslation.h> 
#include <Inventor/nodes/SoComplexity.h>
#include <Inventor/nodes/SoNurbsSurface.h>
#include <Inventor/VRMLnodes/SoVRMLColor.h>
#include <Inventor/VRMLnodes/SoVRMLViewpoint.h>
#include <Inventor/actions/SoRayPickAction.h>
#include <Inventor/VRMLnodes/SoVRMLWorldInfo.h>
#include <Inventor/VRMLnodes/SoVRMLScript.h>
#include <Inventor/VRMLnodes/SoVRMLImageTexture.h>
#include <Inventor/VRMLnodes/SoVRMLAppearance.h>
#include <Inventor/VRMLnodes/SoVRMLTransform.h>
#include <Inventor/VRMLnodes/SoVRMLSwitch.h>
#include <Inventor/VRMLnodes/SoVRMLShape.h>
#include <Inventor/VRMLnodes/SoVRMLMaterial.h>
#include <Inventor/VRMLnodes/SoVRMLCone.h>
#include <Inventor/VRMLnodes/SoVRMLCylinder.h>
#include <Inventor/Qt/SoQtCursor.h>
#include <Inventor/misc/SoBase.h>
#include <Inventor/nodes/SoRotationXYZ.h>
#include <Inventor/engines/SoElapsedTime.h>
#include <Inventor/nodes/SoText3.h>
#include <Inventor/lists/SbStringList.h>
#include <Inventor/nodes/SoText2.h>
#include <Inventor/nodes/SoOrthographicCamera.h>
#include <Inventor/VRMLnodes/SoVRMLBox.h>
#include <Inventor/misc/SoProto.h>
#include <Inventor/details/SoDetail.h>

#endif // SOQTLIB